# Generated by Django 3.1.2 on 2020-11-04 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bandipurBliss', '0002_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='check_in',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='booking',
            name='check_out',
            field=models.DateField(),
        ),
    ]
